{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rasterdiv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rasterdiv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rasterdiv/rasterdiv_{{ version }}.tar.gz
  sha256: ba6e0b60c668d16036bb62b7d527a76b2763e916d8fa930d2db199db4f1951ba

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggforce
    - r-ggplot2
    - r-progress
    - r-proxy
    - r-terra
    - r-twdtw
    - r-viridis
  run:
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggforce
    - r-ggplot2
    - r-progress
    - r-proxy
    - r-terra
    - r-twdtw
    - r-viridis

test:
  commands:
    - $R -e "library('rasterdiv')"           # [not win]
    - "\"%R%\" -e \"library('rasterdiv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rasterdiv
  license: GPL-2.0-or-later
  summary: Providing functions to calculate indices of diversity on numerical matrices based on information theory. The rationale behind the package is described in Rocchini, Marcantonio and Ricotta (2017) <doi:10.1016/j.ecolind.2016.07.039> and Rocchini, Marcantonio,..., Ricotta (2021) <doi:10.1101/2021.01.23.427872>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59
